name: flutter_news_portal
description: Portal de notícias exemplo completo com MVVMC, temas, cadastro, categorias, detalhes e perfil.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  url_launcher: ^6.2.5
  shared_preferences: ^2.0.15
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
